version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pb
    ports:
      - "5000:5000"
    # command: project_backup
    # env_file: .env-local