version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-backup
    ports:
      - "5000:5000"
    # command: project-backup
    # env_file: .env-local